Comparison tool and reference masks's
ign-packo/ShadowT pull request #2
Opened 2021-10-19 13:58 UTC by yoann-apel

Add : 
- accuracy calculation script
- 2 differente references and test masks

2021-11-03 12:38 UTC, amrosu requested changes
Je n'ai pas testé, et en regardant le code, je pense qu'il y a quelques modifications à faire pour que ça fonctionne (notamment chemins indiqués en dur et incorrects).

Voici mes remarques sur le code :

2021-11-03 12:38 UTC, amrosu commented on comparison_mask/DifferenceMask.py
> +false_negative_percentage = (false_negative/total_pixels) * 100
Il ne faut pas faire un pourcentage par rapport aux nombre total de pixels de l'image, mais par rapport au nombre total de pixels positifs (ombre), car c'est cet échantillon qui nous intéresse

2021-11-04 09:30 UTC, yoann-apel commented on comparison_mask/DifferenceMask.py
> +
Effectivement, on s'est dit avec Manchun de faire sur le masque d'ombre de référence, une zone d'incertitude pour laquelle on ne sait pas dire avec certitude si c'est un pixel à l'ombre ou non.

2021-12-03 12:23 UTC, amrosu requested changes

2021-12-06 13:51 UTC, yoann-apel commented on comparison_mask/DifferenceMask.py
> +FN = np.sum(np.logical_and(mask_ref==255,mask_test==0)) # Shadow for reference and not shadow for test mask (false negative)
Des noms de variables plus explicites ?

2021-12-06 16:29 UTC, yoann-apel commented on comparison_mask/DifferenceMask.py
> +mask_test = cv2.imread(src_path_test, 0) # The mask to test with the reference mask
- [ ] Rajouter test

2022-01-12 14:02 UTC, merged

2022-01-13 09:32 UTC, yoann-apel commented
Fusion de la branche trop tôt, demandes de correction non traitées.